from __future__ import annotations

from .base import DocumentTypeRules


HARA_CRITICAL_CLAIMS = (
    "hazard identification",
    "hazardous event",
    "severity rating",
    "exposure rating",
    "controllability rating",
    "ASIL or risk level",
    "safety goal",
    "final acceptability conclusion",
)


HARA_RULES = DocumentTypeRules(
    task_type="hara",
    display_name="HARA 危害分析报告",
    description="面向功能安全分析的 HARA 报告写作任务。",
    default_sections=(
        "文档目的和范围",
        "输入材料和假设",
        "Item definition 摘要",
        "运行场景和模式",
        "危害识别",
        "危险事件分析",
        "S/E/C 评级表",
        "ASIL 候选",
        "安全目标候选",
        "开放问题和必需确认",
        "审查摘要",
    ),
    required_sections=(
        "scope",
        "input materials",
        "item definition",
        "hazard identification",
        "hazardous event analysis",
        "rating table",
        "open issues",
    ),
    optional_sections=(
        "operational situations and modes",
        "ASIL candidate",
        "safety goals candidate",
        "review summary",
    ),
    critical_claims=HARA_CRITICAL_CLAIMS,
    requires_human_confirmation=HARA_CRITICAL_CLAIMS,
    forbidden_final_claims=(
        "final ASIL is approved",
        "final ASIL is",
        "ASIL is confirmed",
        "risk is acceptable",
        "hazard is confirmed",
        "safety goal is approved",
        "final acceptability conclusion",
        "final risk level is",
        "the rating is s1",
        "the rating is s2",
        "the rating is s3",
        "the rating is e1",
        "the rating is e2",
        "the rating is e3",
        "the rating is c1",
        "the rating is c2",
        "the rating is c3",
    ),
    confirmation_marker="NEEDS_USER_CONFIRMATION",
    fact_source_roles=("source",),
    non_fact_source_roles=(
        "sample",
        "template",
        "checklist",
        "reference",
        "expected_output_shape",
    ),
    reference_policy="Reference materials may support methodology/background, but must not prove project-specific facts.",
    sample_policy="Sample documents may guide style and structure but must not be used as fact source.",
    default_final_status="finalized_with_open_items",
    allowed_final_statuses=(
        "finalized_with_open_items",
        "blocked_pending_confirmation",
        "ready_for_human_review",
    ),
    review_focus=(
        "template completeness",
        "checklist coverage",
        "unsupported critical claims",
        "sample misuse",
        "unconfirmed HARA professional judgments",
    ),
    verification_focus=(
        "required artifacts",
        "citation integrity",
        "sample not fact source",
        "critical claims confirmation",
        "candidate update inactive",
    ),
    candidate_learning_policy="Generate candidate updates only; keep proposed/inactive unless explicitly approved.",
    terminology={
        "sensitive_title_markers": "hazard|hazardous|rating|s/e/c|asil|risk|safety goal|危害|危险事件|评级|风险|安全目标",
        "rating_title_markers": "s/e/c|rating|asil|risk|评级|风险",
        "rating_placeholder": "S? / E? / C?",
        "professional_judgment": "HARA professional judgment",
        "professional_judgments": "HARA professional judgments",
        "critical_claims_label": "HARA critical claims",
    },
    output_labels={
        "draft_title": "HARA 危害分析报告保守草稿",
        "final_report_title": "HARA 危害分析报告最终交付包",
        "confirmation_section": "NEEDS_USER_CONFIRMATION",
        "open_items_heading": "HARA 开放确认项",
    },
)
